apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: todoapp
spec:
  containers:
  - name: todoapp
    image: iryna0629/todoapp:3.0.0
    ports:
    - containerPort: 8000
    readinessProbe:
      httpGet:
        path: /ready/
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /health/
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 20
