apiVersion: v1
kind: Pod
metadata:
    name: todoapp
    namespace: todoapp
spec:
    containers:
    - name: todoapp-cont
      image: pochtalon/todoapp:3.0.0
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
