apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
spec:
  containers:
  - name: todoapp
    image: yaroslavya27/todoapp:3.0.0
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /readiness
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /liveness/
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
