apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: todoapp
spec:
  containers:
    - name: todoapp
      image: lavryniuk/todoapp:3.0.0
      ports:
        - containerPort: 8081
      livenessProbe:
        httpGet:
          path: api/health
          port: 8081
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: api/ready
          port: 8081
        initialDelaySeconds: 5
        periodSeconds: 5
        