apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
spec:
  containers:
  - name: busybox
    image: ikulyk404/busyboxplus:curl
    command: ["sh", "-c", "while true; do echo hello; sleep 10;done"]
