apiVersion: v1
kind: Pod
metadata:
  name: busybox-curl
  namespace: todoapp
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ["sleep", "1000"]