apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
spec:
  containers:
    - name: busybox
      image: greena1c/todoapp:3.0.0
      ports:
      - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /api/readiness
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /api/liveness
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10 