apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: garimanblack/todoapp:3.0.0
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /api/liveness_check
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /api/readiness_check
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
