apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  labels:
    role: todoapp
spec:
  containers:
    - name: todoapp
      image: vpcomtek/todoapp:3.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - name: todoapp
          containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: api/liveness
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: api/readiness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
  