apiVersion: v1             
kind: Pod
metadata:       
 name: todoapp
 namespace: todoapp
 labels:
 app: todoapp
spec:
 containers:
 - name: todoapp
   image: kagerou4649/todoapp:3.0.0
   ports:
   - containerPort: 8080
   livenessProbe:
     httpGet:    
       path: api/liveness
       port: 8080
     initialDelaySeconds: 40
     periodSeconds: 5 
   readinessProbe:
     httpGet:
       path: api/ready 
       port: 8080
     initialDelaySeconds: 5 
     periodSeconds: 5
