apiVersion: v1
kind: Pod

metadata:
  name: todoapp-pod
  namespace: todoapp

spec:
  containers:
  - name: todoapp
    image: fredisson11/todoapp:3.0.0
    
    ports:
    - containerPort: 8080
    
    livenessProbe:
      httpGet:
        path: /liveness
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

    readinessProbe:
      httpGet:
        path: /readiness
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5