apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: andr1yk/todoapp:3.0.6
      ports:
       - containerPort: 8080
      readinessProbe:
        httpGet:
          path: api/health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: api/ready
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
