apiVersion: v1
kind: Pod
metadata:
    name: todoapppod
    namespace: todoapp
spec:
    containers:
    - name: todoappcontainer
      image: yegorv/todoapp:3.0.0
      ports:
      - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /api/liveness/
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /api/readiness/
          port: 8080
        initialDelaySeconds: 40
        periodSeconds: 20
