apiVersion: v1
kind: Pod
metadate:
  name: todoapp:3.0.0
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: limbx/todoapp:3.0.0
      ports:
      - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /api/liveness
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /api/readiness
        port:8080
      initialDelaySeconds: 5
      periodSeconds: 5
  