apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: mateapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: vshvanska/todoapp
      ports:
       - containerPort: 8080
      livenessProbe:
        httpGet:
          path: api/health
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: api/ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
