apiVersion: v1
kind: Pod
metadata:
  name: todoapp
spec:
  containers:
    - name: todoapp
      image: krillpolozenko/todoapp:3.0.0
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /liveness
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          memory: "256Mi"
          cpu: "1000m"
