apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp
    image: nemereno/todoapp:3.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
       path: api/healthz
       port: 8080
      initialDelaySeconds: 60
      periodSeconds: 3
    readinessProbe:
      httpGet:
       path: api/ready
       port: 8080
      initialDelaySeconds: 5
      periodSeconds: 3
