FROM python:3.12-slim as base

WORKDIR /app

COPY .   ./

RUN pip install --no-cache-dir -r requirements.txt && \
    python manage.py migrate

ENV PYTHONUNBUFFERED=1

EXPOSE 8080

ENTRYPOINT python manage.py runserver 0.0.0.0:8080
